include:
  - https://invent.kde.org/sysadmin/ci-tooling/raw/master/invent/ci-before.yml

variables:
  PRODUCT: Applications

linux kf5-qt5 qt5.15:
  image: "kdeorg/ci-suse-qt515"
  extends: .linux
  variables:
    PLATFORM: SUSEQt5.15
    BRANCH_GROUP: kf5-qt5
